version: "3.7"
services:
  db:
    image: postgres:alpine
    env_file:
      - local.env
    ports:
      - 5432:5432
    volumes:
      - "./pgdata/data:/var/lib/postgresql/data:rw"
    networks:
      - cowork-network
  cowork_site:
    build: .
    command: sh -c './wait-for-it.sh db:5432 && alembic upgrade head && uwsgi --yaml /app/uwsgi.yml'
    links:
      - db
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - "./migrations/versions/:/app/migrations/versions/:rw"
      - "./:/app/:rw"
    env_file:
      - local.env
    networks:
      - cowork-network

networks:
  cowork-network:
