version: "3.7"
services:
  dd-agent:
    image: datadog/agent:7
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc/:/host/proc/:ro"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
    env_file:
      - prod.env
    networks:
      - cowork-network
  nginx:
    image: nginx:alpine
    env_file:
      - prod.env
    links:
      - cowork_site
    depends_on:
      - cowork_site
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/logs:/var/log/nginx/:rw"
      - "./cowork_site/static:/static:ro"
      - '/etc/letsencrypt/live/cowork19.club-0001/fullchain.pem:/certs/fullchain.pem:ro'
      - '/etc/letsencrypt/live/cowork19.club-0001/privkey.pem:/certs/privkey.pem:ro'
    networks:
      - cowork-network
  db:
    image: postgres:alpine
    env_file:
      - prod.env
    ports:
      - 5432:5432
    volumes:
      - "./pgdata/data:/var/lib/postgresql/data:rw"
    networks:
      - cowork-network
  cowork_site:
    build: .
    command: sh -c './wait-for-it.sh db:5432 && alembic upgrade head && uwsgi --yaml /app/uwsgi.yml'
    links:
      - db
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - "./:/app/:ro"
      - "./migrations/versions/:/app/migrations/versions/:ro"
    env_file:
      - prod.env
    networks:
      - cowork-network

networks:
  cowork-network:
