version: "3.7"
services:
  dd-agent:
    image: datadog/agent:7
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc/:/host/proc/:ro"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
    ports:
      - 8126:8126
    links:
      - cowork_site
    depends_on:
      - cowork_site
    env_file:
      - local.env
    networks:
      - cowork-network
    logging:
      driver: none
  nginx:
    image: nginx:alpine
    env_file:
      - local.env
    links:
      - cowork_site
    depends_on:
      - cowork_site
    ports:
      - 80:80
    volumes:
      - "./nginx/nginx_local.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/logs:/var/log/nginx/:rw"
      - "./cowork_site/static:/static:ro"
    networks:
      - cowork-network
  db:
    image: postgres:alpine
    env_file:
      - local.env
    ports:
      - 5432:5432
    volumes:
      - "./pgdata/data:/var/lib/postgresql/data:rw"
    networks:
      - cowork-network
  cowork_site:
    build: .
    command: sh -c './wait-for-it.sh db:5432 && alembic upgrade head && uwsgi --yaml /app/uwsgi.yml'
    links:
      - db
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - "./:/app/:ro"
      - "./migrations/versions/:/app/migrations/versions/:rw"
    env_file:
      - local.env
    networks:
      - cowork-network
  redis:
    image: redis:alpine
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server", "--save", ""]
    links:
      - cowork_site
    depends_on:
      - cowork_site
    ports:
      - 6379:6379
    env_file:
      - local.env
    networks:
      - cowork-network
    logging:
      driver: none

networks:
  cowork-network:
