"""Make contact optional

Revision ID: 632988a05ad0
Revises: 54d716d9a7d3
Create Date: 2020-04-12 09:43:39.836397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632988a05ad0'
down_revision = '54d716d9a7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posting_need_work', 'contact',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posting_need_work', 'contact',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
