"""Contact optional too

Revision ID: 68bddc9b137d
Revises: 632988a05ad0
Create Date: 2020-04-12 09:51:12.863938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bddc9b137d'
down_revision = '632988a05ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posting_need_team', 'contact',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posting_need_team', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posting_need_work', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posting_need_work', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posting_need_team', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posting_need_team', 'contact',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
